#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoodleStats.Droid.Resource", IsApplication=true)]

namespace MoodleStats.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::EggsToGo.Resource.String.library_name = global::MoodleStats.Droid.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int timeSpinner = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fullLogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int SpinnerStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Style_btnCreateAccount = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Style_btnLogin = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int btnCourseSelect = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int btnCreateAccount = 2131099666;
			
			// aapt resource value: 0x7f060007
			public const int btnCreateAccountDialog = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int btnLogin = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int btnLoginDialog = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int btnSelectCourse = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int dialog_login = 2131099656;
			
			// aapt resource value: 0x7f060017
			public const int imgLogo = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int layoutLin = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int layoutLinear = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int pgsBar = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int spinCourse = 2131099661;
			
			// aapt resource value: 0x7f060018
			public const int spnSplah = 2131099672;
			
			// aapt resource value: 0x7f060009
			public const int t = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int txtCreate = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int txtEmail = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int txtLocation = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int txtMoodlePassword = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int txtNewPassword = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int txtOR = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int txtPassword = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int txtUsername = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int txtfName = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int txtlName = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int winChartLayout = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_createAccount = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_SelectCourse = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int winGraph = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int winSplash = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int btnBack = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int btnCreateAccount = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int btnLogin = 2130968579;
			
			// aapt resource value: 0x7f040011
			public const int btnShowGraph = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040013
			public const int spnSelectCourse = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int timeSpinnerPrompt = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int txtBarYear = 2130968596;
			
			// aapt resource value: 0x7f04000f
			public const int txtCourseSelection = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int txtCreate = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int txtEmail = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int txtLocation = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int txtLogin = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int txtMoodlePassword = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int txtNewPassword = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int txtPassword = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int txtTime = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int txtUsername = 2130968589;
			
			// aapt resource value: 0x7f040007
			public const int txtfName = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int txtlName = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
